### PR TITLE
Use object instead of array for points

### PR DESCRIPTION
**Pull request by diazruy**
First time it didn't work for me either, because I was doing
```javascript
this.path.push(this.position);
```
but that was assigning the **same** object (by reference). So every time I updated `this.position.x`, it was changing the value for _all_ entries in the Array (since they were all pointing to the **same** object. Now, in the `addPoint` method, I'm pushing a _new_ object every time.

### CODE REVIEW

**Comment by rosadiaz** [comment]
I dont see the benefit of using an object 🤔🤔🤔🤔🤔

**Comment by diazruy** [comment]
What's more expressive? `
```
point[0]
point[1]
```
vs
```
point.x
point.y
```
what's clearer 6 months from now when you come back and look at the code?

**Comment by rosadiaz** [comment]
Que le hago a este branch ahora? Ya entregue la tarea? @diazruy

**Comment by diazruy** [comment]
Dale "Close Pull Request" (aqui hasta abajo), despues de lo cual te va a aparecer el boton de "Delete branch". 
selection_057


O si no, desde tu terminal `git push origin :turtle-objects`, lo cual dice "retacale (push) a Github (origin) "nada" (`:`) al branch remoto  llamado turtle-objects

**Pull request closed without merging**
